meta_product_name: "Pinky Girls"
meta_title: "Brothel escort in Auckland"
meta_description: "auckland escort - escorts auckland brothel with escort girl , Massage Parlour , Escort Agency"
meta_image: "pinkygirls.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
